### PR TITLE
Added command to the command line to graph the revisions enriched with the pdt release information.

### PR DESCRIPTION
**Pull request by hvdklauw**

### CODE REVIEW

**Comment by hvdklauw** [comment]
Also depends on paylogic/alembic-offline#1

**Comment by bubenkoff** [comment]
strange thing about tests
i think we need to fix the version of requests library, i mean minimum version
because since some point it starts to capitalize content-type

**Comment by hvdklauw** [comment]
Nope.
We call it with Content-Type so then the mock gets that too, don't know why it worked before.

**Comment by bubenkoff** [comment]
please cover label_callback
https://coveralls.io/builds/3424805/source?filename=pdt_client%2Fcommands.py#L305

**Comment by hvdklauw** [comment]
Had to change the code around a bit, also covered the KeyError.

**Comment by bubenkoff** [comment]
1.3.0 is out

**Pull request merged**
